# Generated by Django 5.0.6 on 2024-06-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0004_alter_uploadedfile_cost_alter_uploadedfile_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_files/'),
        ),
    ]
